-- --------------------------------------------------------
-- 호스트:                          127.0.0.1
-- 서버 버전:                        10.4.12-MariaDB - mariadb.org binary distribution
-- 서버 OS:                        Win64
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- shop 데이터베이스 구조 내보내기
CREATE DATABASE IF NOT EXISTS `shop` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `shop`;

-- 테이블 shop.category 구조 내보내기
CREATE TABLE IF NOT EXISTS `category` (
  `CATEGORY_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`CATEGORY_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.category_detail 구조 내보내기
CREATE TABLE IF NOT EXISTS `category_detail` (
  `CATEGORY_DETAIL_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_NUM` int(11) NOT NULL,
  `CATEGORY_DETAIL_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`CATEGORY_DETAIL_NUM`),
  KEY `CATEGORY_NUM` (`CATEGORY_NUM`),
  CONSTRAINT `FK_CATEGORY_NUM_CATEGORY_DETAIL` FOREIGN KEY (`CATEGORY_NUM`) REFERENCES `category` (`CATEGORY_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.faq 구조 내보내기
CREATE TABLE IF NOT EXISTS `faq` (
  `FAQ_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `FAQ_TITLE` varchar(50) NOT NULL,
  `FAQ_CONTENT` varchar(200) NOT NULL,
  `FAQ_CATEGORY` varchar(20) NOT NULL,
  PRIMARY KEY (`FAQ_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.order 구조 내보내기
CREATE TABLE IF NOT EXISTS `order` (
  `ORDER_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(100) NOT NULL,
  `RECIP_NAME` varchar(50) NOT NULL,
  `RECIP_TEL` varchar(11) NOT NULL,
  `RECIP_ADD_NUM` varchar(20) NOT NULL,
  `RECIP_ADD` varchar(100) NOT NULL,
  `RECIP_ADD_DETAIL` varchar(100) NOT NULL,
  `PAY_CATEGORY` varchar(20) NOT NULL,
  `ORDER_MSG` varchar(100) NOT NULL,
  `ORDER_PRICE` varchar(100) NOT NULL,
  `ORDER_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ORDER_NUM`),
  KEY `FK_USER_ID_ORDER` (`USER_ID`),
  CONSTRAINT `FK_USER_ID_ORDER` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.orderlist 구조 내보내기
CREATE TABLE IF NOT EXISTS `orderlist` (
  `ORDERLIST_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_NUM` int(11) NOT NULL,
  `ORDERLIST_AMOUNT` int(10) NOT NULL,
  `ORDERLIST_PRICE` int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ORDERLIST_NUM`,`PRODUCT_NUM`),
  KEY `FK_PRODUCT_NUM_ORDERLIST` (`PRODUCT_NUM`),
  CONSTRAINT `FK_PRODUCT_NUM_ORDERLIST` FOREIGN KEY (`PRODUCT_NUM`) REFERENCES `product` (`PRODUCT_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.product 구조 내보내기
CREATE TABLE IF NOT EXISTS `product` (
  `PRODUCT_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` varchar(100) NOT NULL,
  `PRODUCT_PRICE` int(10) NOT NULL DEFAULT 0,
  `PRODUCT_INFO` varchar(100) NOT NULL,
  `PRODUCT_THUMBNAIL` varchar(100) DEFAULT NULL,
  `PRODUCT_STATE` varchar(50) NOT NULL,
  `PRODUCT_AMOUNT` int(10) NOT NULL DEFAULT 0,
  `PRODUCT_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `CATEGORY_DETAIL_NUM` int(11) NOT NULL,
  PRIMARY KEY (`PRODUCT_NUM`),
  KEY `FK_CATEGORY_DETAIL_NUM_PRODUCT` (`CATEGORY_DETAIL_NUM`),
  CONSTRAINT `FK_CATEGORY_DETAIL_NUM_PRODUCT` FOREIGN KEY (`CATEGORY_DETAIL_NUM`) REFERENCES `category_detail` (`CATEGORY_DETAIL_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.product_board 구조 내보내기
CREATE TABLE IF NOT EXISTS `product_board` (
  `PRODUCT_BOARD_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_NUM` int(11) NOT NULL,
  `USER_ID` varchar(100) NOT NULL,
  `PRODUCT_BOARD_CATEGORY` varchar(20) NOT NULL,
  `PRODCUT_BOARD_TITLE` varchar(100) NOT NULL,
  `PRODUCT_BOARD_CONTENT` varchar(200) NOT NULL,
  `PRODUCT_BOARD_IMG` varchar(200) DEFAULT NULL,
  `PRODUCT_BOARD_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`PRODUCT_BOARD_NUM`),
  KEY `FK_PRODUCT_NUM_PRODUCT_BOARD` (`PRODUCT_NUM`),
  KEY `FK_USER_ID_PRODUCT_BOARD` (`USER_ID`),
  CONSTRAINT `FK_PRODUCT_NUM_PRODUCT_BOARD` FOREIGN KEY (`PRODUCT_NUM`) REFERENCES `product` (`PRODUCT_NUM`),
  CONSTRAINT `FK_USER_ID_PRODUCT_BOARD` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.product_board_reply 구조 내보내기
CREATE TABLE IF NOT EXISTS `product_board_reply` (
  `REPLY_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_BOARD_NUM` int(11) NOT NULL,
  `REPLY_CONTENT` varchar(200) NOT NULL,
  `REPLY_IMG` varchar(200) NOT NULL,
  `REPLY_DATE` datetime NOT NULL,
  PRIMARY KEY (`REPLY_NUM`),
  KEY `FK_PRODUCT_BOARD_NUM_REPLY` (`PRODUCT_BOARD_NUM`),
  CONSTRAINT `FK_PRODUCT_BOARD_NUM_REPLY` FOREIGN KEY (`PRODUCT_BOARD_NUM`) REFERENCES `product_board` (`PRODUCT_BOARD_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.product_img 구조 내보내기
CREATE TABLE IF NOT EXISTS `product_img` (
  `PRODUCT_IMG_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_NUM` int(11) NOT NULL,
  `PRODUCT_IMG` varchar(200) NOT NULL DEFAULT '',
  `PRODCUT_IMG_STATE` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`PRODUCT_IMG_NUM`),
  KEY `FK_PRODUCT_NUM_PRODUCT_IMG` (`PRODUCT_NUM`),
  CONSTRAINT `FK_PRODUCT_NUM_PRODUCT_IMG` FOREIGN KEY (`PRODUCT_NUM`) REFERENCES `product` (`PRODUCT_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.service 구조 내보내기
CREATE TABLE IF NOT EXISTS `service` (
  `SERVICE_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(100) NOT NULL,
  `SERVICE_TITLE` varchar(50) NOT NULL,
  `SERVICE_CONTENT` varchar(200) NOT NULL,
  `SERVICE_IMG` varchar(200) NOT NULL,
  `SERVICE_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `SERVICE_STATE` varchar(10) NOT NULL DEFAULT '답변대기',
  PRIMARY KEY (`SERVICE_NUM`),
  KEY `FK_USER_ID_SERVICE` (`USER_ID`),
  CONSTRAINT `FK_USER_ID_SERVICE` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.service_reply 구조 내보내기
CREATE TABLE IF NOT EXISTS `service_reply` (
  `SERVICE_REPLY_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `SERVICE_NUM` int(11) NOT NULL,
  `SERVICE_REPLY_CONTENT` varchar(200) NOT NULL,
  `SERVICE_REPLY_IMG` varchar(200) NOT NULL,
  `SERVICE_REPLY_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`SERVICE_REPLY_NUM`),
  KEY `FK_SERVICE_NUM_REPLY` (`SERVICE_NUM`),
  CONSTRAINT `FK_SERVICE_NUM_REPLY` FOREIGN KEY (`SERVICE_NUM`) REFERENCES `service` (`SERVICE_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 shop.user 구조 내보내기
CREATE TABLE IF NOT EXISTS `user` (
  `USER_ID` varchar(100) NOT NULL,
  `USER_PASS` varchar(100) NOT NULL,
  `USER_NICKNAME` varchar(50) NOT NULL,
  `USER_TEL` varchar(11) NOT NULL,
  `USER_RULE` varchar(10) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 내보낼 데이터가 선택되어 있지 않습니다.

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
